<a href="https://colab.research.google.com/github/teju2807/Machine_Learning_Projects/blob/main/Placement_Predication_Using_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import library

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df= pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Placement.csv')

In [5]:
df.head()

Student_ID  CGPA   IQ  Placement
0           1   6.8  123          1
1           2   5.9  106          0
2           3   5.3  121          0
3           4   7.4  132          1
4           5   5.8  142          0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Student_ID  100 non-null    int64  
 1   CGPA        100 non-null    float64
 2   IQ          100 non-null    int64  
 3   Placement   100 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 3.2 KB


In [8]:
df.describe()

Student_ID        CGPA          IQ   Placement
count  100.000000  100.000000  100.000000  100.000000
mean    50.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      1.000000    3.300000   37.000000    0.000000
25%     25.750000    5.075000  101.500000    0.000000
50%     50.500000    6.000000  127.500000    0.500000
75%     75.250000    6.900000  149.000000    1.000000
max    100.000000    8.500000  233.000000    1.000000

In [9]:
df.isna().sum()

Student_ID    0
CGPA          0
IQ            0
Placement     0
dtype: int64

In [10]:
df.columns

Index(['Student_ID', 'CGPA', 'IQ', 'Placement'], dtype='object')

In [11]:
df.shape

(100, 4)

Define X and y variables

In [12]:
y=df['Placement']

In [13]:
y

0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    0
97    1
98    1
99    1
Name: Placement, Length: 100, dtype: int64

In [14]:
y.shape

(100,)

In [15]:
X = df[['CGPA', 'IQ']]

In [16]:
X.shape

(100, 2)

In [17]:
X

CGPA   IQ
0    6.8  123
1    5.9  106
2    5.3  121
3    7.4  132
4    5.8  142
..   ...  ...
95   4.3  200
96   4.4   42
97   6.7  182
98   6.3  103
99   6.2  113

[100 rows x 2 columns]

Standardized X variable

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
ss = StandardScaler()

In [20]:
X=ss.fit_transform(X)

In [21]:
X

array([[ 0.71095807, -0.01459341],
       [-0.0799718 , -0.44233119],
       [-0.60725838, -0.0649155 ],
       [ 1.23824465,  0.21185601],
       [-0.16785289,  0.46346647],
       [ 0.97460136, -1.90167186],
       [-0.25573399,  0.48862751],
       [-0.87090167, -1.52425617],
       [ 0.0957904 ,  0.81572111],
       [-0.78302057, -1.44877303],
       [ 0.0079093 , -1.977155  ],
       [ 0.79883917,  0.36282228],
       [-0.51937728,  0.38798333],
       [ 0.35943369, -0.19072073],
       [ 0.0957904 , -0.51781433],
       [-0.78302057,  1.31894203],
       [-0.69513948,  2.52667224],
       [-2.36488031,  1.49506935],
       [-1.74971264, -0.59329747],
       [-0.69513948,  0.21185601],
       [ 0.53519588, -0.09007654],
       [ 0.97460136,  0.68991588],
       [-0.95878277, -0.09007654],
       [-1.13454496, -0.92039106],
       [-1.13454496, -0.0649155 ],
       [-0.87090167, -0.81974688],
       [ 0.88672027,  1.89764609],
       [ 0.0079093 ,  0.01056764],
       [-0.69513948,

Train Test Split

In [22]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=2807,stratify=y)

In [32]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((70, 2), (30, 2), (70,), (30,))

Model Selection

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
lr=LogisticRegression()

In [35]:
lr.fit(X_train,y_train)

LogisticRegression()

Prediction

In [36]:
y_pred = lr.predict(X_test)

In [37]:
y_pred.shape

(30,)

In [38]:
y_pred

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0])

In [39]:
lr.predict_proba(X_test)

array([[1.83530540e-01, 8.16469460e-01],
       [9.42733632e-01, 5.72663677e-02],
       [1.37935877e-03, 9.98620641e-01],
       [4.59404123e-01, 5.40595877e-01],
       [9.51078742e-01, 4.89212584e-02],
       [2.64258798e-01, 7.35741202e-01],
       [1.97782725e-02, 9.80221727e-01],
       [4.08130020e-01, 5.91869980e-01],
       [9.64150534e-01, 3.58494656e-02],
       [2.57754388e-02, 9.74224561e-01],
       [4.31360055e-03, 9.95686399e-01],
       [3.77133803e-01, 6.22866197e-01],
       [8.95030143e-01, 1.04969857e-01],
       [8.68655443e-01, 1.31344557e-01],
       [9.26991654e-01, 7.30083456e-02],
       [2.66480032e-02, 9.73351997e-01],
       [9.66780927e-01, 3.32190731e-02],
       [9.99089532e-01, 9.10467937e-04],
       [2.13679023e-02, 9.78632098e-01],
       [9.78890317e-01, 2.11096834e-02],
       [9.23057391e-02, 9.07694261e-01],
       [3.26340039e-01, 6.73659961e-01],
       [8.45552305e-02, 9.15444769e-01],
       [4.52438822e-03, 9.95475612e-01],
       [9.917144

In [41]:
from sklearn.metrics import confusion_matrix , classification_report

In [42]:
print(confusion_matrix(y_test,y_pred))

[[14  1]
 [ 0 15]]


In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.94      1.00      0.97        15

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



Future Prediction

In [46]:
X_new= df.sample(1)

In [47]:
X_new

Student_ID  CGPA   IQ  Placement
50          51   3.5  233          0

In [48]:
X_new.shape

(1, 4)

In [50]:
X_new=X_new.drop(['Student_ID','Placement'],axis=1)

In [51]:
X_new

CGPA   IQ
50   3.5  233

In [52]:
X_new=ss.fit_transform(X_new)

In [53]:
y_pred_new=lr.predict(X_new)

In [54]:
y_pred_new

array([0])

In [55]:
lr.predict_proba(X_new)

array([[0.52065001, 0.47934999]])